// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPhotoBiz.Data;

#nullable disable

namespace myPhotoBiz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260115012352_AddClientFolderLink")]
    partial class AddClientFolderLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GalleryAlbum", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlbumId", "GalleryId");

                    b.HasIndex("GalleryId");

                    b.ToTable("GalleryAlbum");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Activity_CreatedAt");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("IX_Activity_EntityType");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Activity_UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoShootId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("PhotoShootId")
                        .HasDatabaseName("IX_Album_PhotoShootId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPhotographer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoAward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequiredContractId");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AlternativeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeclinedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedDurationHours")
                        .HasColumnType("REAL");

                    b.Property<double?>("EstimatedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoShootId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhotographerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PreferredDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PreferredStartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServicePackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialRequirements")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique()
                        .HasDatabaseName("IX_BookingRequest_Reference");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("PhotoShootId");

                    b.HasIndex("PhotographerProfileId");

                    b.HasIndex("PreferredDate")
                        .HasDatabaseName("IX_BookingRequest_PreferredDate");

                    b.HasIndex("ServicePackageId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BookingRequest_Status");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Client_Email");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ClientBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("ContractId");

                    b.ToTable("ClientBadges");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ClientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactPreference")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralDetails")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferralSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientProfile_UserId");

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AwardBadgeOnSign")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BadgeToAwardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoShootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BadgeToAwardId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("PhotoShootId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ContractTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AwardBadgeOnSign")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BadgeToAwardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTemplate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFilePathTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BadgeToAwardId");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ContractTemplate_Category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ContractTemplate_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_ContractTemplate_Name");

                    b.ToTable("ContractTemplates");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.FileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SharedWith")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.FileItemTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileItemId");

                    b.HasIndex("TagId");

                    b.ToTable("FileItemTags");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowPublicAccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#2c3e50");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Gallery_IsActive");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.GalleryAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanProof")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_GalleryAccess_ExpiryDate");

                    b.HasIndex("GalleryId", "ClientProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_GalleryAccess_Gallery_ClientProfile");

                    b.ToTable("GalleryAccesses");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.GallerySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_GallerySession_CreatedDate");

                    b.HasIndex("GalleryId")
                        .HasDatabaseName("IX_GallerySession_GalleryId");

                    b.HasIndex("SessionToken")
                        .IsUnique()
                        .HasDatabaseName("IX_GallerySession_SessionToken");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_GallerySession_UserId");

                    b.ToTable("GallerySessions");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<double>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DepositPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DepositPaidDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRecurrenceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoShootId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecurrencePattern")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReminderSentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientProfileId")
                        .HasDatabaseName("IX_Invoice_ClientProfileId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Invoice_IsDeleted");

                    b.HasIndex("PhotoShootId")
                        .HasDatabaseName("IX_Invoice_PhotoShootId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.MinorModelRelease", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcceptanceMethod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JurisdictionState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageRights")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("ClientProfileId");

                    b.ToTable("MinorModelReleases");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ModelRelease", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcceptanceMethod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JurisdictionState")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageRights")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("ClientProfileId");

                    b.ToTable("ModelReleases");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PackageAddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStandalone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ServicePackageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsStandalone")
                        .HasDatabaseName("IX_PackageAddOn_IsStandalone");

                    b.HasIndex("ServicePackageId");

                    b.ToTable("PackageAddOns");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_Payment_InvoiceId");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_Payment_PaymentDate");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_Payment_TransactionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ClientProfileId")
                        .HasDatabaseName("IX_Photo_ClientProfileId");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_Photo_DisplayOrder");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotoShoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRecurrenceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotographerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrencePattern")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShootType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_PhotoShoot_IsDeleted");

                    b.HasIndex("PhotographerProfileId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PhotoShoots");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotographerAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookingRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotographerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurringDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingRequestId");

                    b.HasIndex("PhotographerProfileId", "StartTime")
                        .HasDatabaseName("IX_PhotographerAvailability_Photographer_StartTime");

                    b.ToTable("PhotographerAvailabilities");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotographerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialties")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PhotographerProfile_UserId");

                    b.ToTable("PhotographerProfiles");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PrintItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinishType")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrintOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("PrintOrderId");

                    b.ToTable("PrintItems");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PrintOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GallerySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintLabOrderId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProofId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RefundedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_PrintOrder_CreatedDate");

                    b.HasIndex("GallerySessionId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PrintOrder_OrderNumber");

                    b.HasIndex("ProofId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PrintOrder_Status");

                    b.ToTable("PrintOrders");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PrintPricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinishType")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Size", "FinishType")
                        .IsUnique()
                        .HasDatabaseName("IX_PrintPricing_Size_FinishType");

                    b.ToTable("PrintPricings");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Proof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditingNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GallerySessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMarkedForEditing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SelectedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GallerySessionId");

                    b.HasIndex("IsFavorite")
                        .HasDatabaseName("IX_Proof_IsFavorite");

                    b.HasIndex("IsMarkedForEditing")
                        .HasDatabaseName("IX_Proof_IsMarkedForEditing");

                    b.HasIndex("PhotoId", "GallerySessionId")
                        .HasDatabaseName("IX_Proof_PhotoId_SessionId");

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("IX_RolePermissions_RoleId_Permission");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ServicePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationHours")
                        .HasColumnType("REAL");

                    b.Property<string>("IncludedFeatures")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("IncludedPhotos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludesAlbum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludesDigitalGallery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludesPrints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfLocations")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfPrints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutfitChanges")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ServicePackage_Category");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_ServicePackage_DisplayOrder");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ServicePackage_IsActive");

                    b.ToTable("ServicePackages");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("GalleryAlbum", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.Gallery", null)
                        .WithMany()
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Activity", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Album", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.PhotoShoot", "PhotoShoot")
                        .WithMany("Albums")
                        .HasForeignKey("PhotoShootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("PhotoShoot");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.BookingRequest", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany("BookingRequests")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.PhotoShoot", "PhotoShoot")
                        .WithMany()
                        .HasForeignKey("PhotoShootId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.PhotographerProfile", "PhotographerProfile")
                        .WithMany()
                        .HasForeignKey("PhotographerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.ServicePackage", "ServicePackage")
                        .WithMany("BookingRequests")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientProfile");

                    b.Navigation("PhotoShoot");

                    b.Navigation("PhotographerProfile");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Client", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ClientBadge", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Badge", "Badge")
                        .WithMany("ClientBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.Client", null)
                        .WithMany("ClientBadges")
                        .HasForeignKey("ClientId");

                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany("ClientBadges")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.Contract", "Contract")
                        .WithMany("ClientBadges")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Badge");

                    b.Navigation("ClientProfile");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ClientProfile", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.FileItem", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId");

                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("MyPhotoBiz.Models.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Contract", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Badge", "BadgeToAward")
                        .WithMany()
                        .HasForeignKey("BadgeToAwardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.Client", null)
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId");

                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.PhotoShoot", "PhotoShoot")
                        .WithMany("Contracts")
                        .HasForeignKey("PhotoShootId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BadgeToAward");

                    b.Navigation("ClientProfile");

                    b.Navigation("PhotoShoot");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ContractTemplate", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Badge", "BadgeToAward")
                        .WithMany()
                        .HasForeignKey("BadgeToAwardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BadgeToAward");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.FileItem", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.FileItem", "ParentFolder")
                        .WithMany("Children")
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.FileItemTag", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.FileItem", "FileItem")
                        .WithMany("FileItemTags")
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.Tag", "Tag")
                        .WithMany("FileItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.GalleryAccess", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany("GalleryAccesses")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.Gallery", "Gallery")
                        .WithMany("Accesses")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.GallerySession", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Gallery", "Gallery")
                        .WithMany("Sessions")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Gallery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Invoice", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Client", null)
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId");

                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.PhotoShoot", "PhotoShoot")
                        .WithMany("Invoices")
                        .HasForeignKey("PhotoShootId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientProfile");

                    b.Navigation("PhotoShoot");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.InvoiceItem", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.MinorModelRelease", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ModelRelease", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Notification", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PackageAddOn", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ServicePackage", "ServicePackage")
                        .WithMany("AddOns")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Payment", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Photo", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotoShoot", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Client", null)
                        .WithMany("PhotoShoots")
                        .HasForeignKey("ClientId");

                    b.HasOne("MyPhotoBiz.Models.ClientProfile", "ClientProfile")
                        .WithMany("PhotoShoots")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.PhotographerProfile", "PhotographerProfile")
                        .WithMany("AssignedPhotoShoots")
                        .HasForeignKey("PhotographerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientProfile");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PhotographerProfile");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotographerAvailability", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.BookingRequest", "BookingRequest")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.PhotographerProfile", "PhotographerProfile")
                        .WithMany()
                        .HasForeignKey("PhotographerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingRequest");

                    b.Navigation("PhotographerProfile");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotographerProfile", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.ApplicationUser", "User")
                        .WithOne("PhotographerProfile")
                        .HasForeignKey("MyPhotoBiz.Models.PhotographerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PrintItem", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.PrintOrder", "PrintOrder")
                        .WithMany("Items")
                        .HasForeignKey("PrintOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("PrintOrder");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PrintOrder", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.GallerySession", "Session")
                        .WithMany()
                        .HasForeignKey("GallerySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPhotoBiz.Models.Proof", null)
                        .WithMany("PrintOrders")
                        .HasForeignKey("ProofId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Proof", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.GallerySession", "Session")
                        .WithMany("Proofs")
                        .HasForeignKey("GallerySessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyPhotoBiz.Models.Photo", "Photo")
                        .WithMany("Proofs")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.RolePermission", b =>
                {
                    b.HasOne("MyPhotoBiz.Models.Permission", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Album", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ApplicationUser", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("PhotographerProfile");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Badge", b =>
                {
                    b.Navigation("ClientBadges");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.BookingRequest", b =>
                {
                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Client", b =>
                {
                    b.Navigation("ClientBadges");

                    b.Navigation("Contracts");

                    b.Navigation("Invoices");

                    b.Navigation("PhotoShoots");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ClientProfile", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("ClientBadges");

                    b.Navigation("Contracts");

                    b.Navigation("GalleryAccesses");

                    b.Navigation("Invoices");

                    b.Navigation("PhotoShoots");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Contract", b =>
                {
                    b.Navigation("ClientBadges");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.FileItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FileItemTags");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Gallery", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.GallerySession", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Photo", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotoShoot", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Contracts");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PhotographerProfile", b =>
                {
                    b.Navigation("AssignedPhotoShoots");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.PrintOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Proof", b =>
                {
                    b.Navigation("PrintOrders");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.ServicePackage", b =>
                {
                    b.Navigation("AddOns");

                    b.Navigation("BookingRequests");
                });

            modelBuilder.Entity("MyPhotoBiz.Models.Tag", b =>
                {
                    b.Navigation("FileItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
